Repository gigantum/gigantum-client, pull requests merged in 2018-10, with the labels that each got.

#95 21: Update to new base-images repository and remove deprecated code
  packages/gtmapi/lmsrvlabbook/api/connections/environment.py
  packages/gtmapi/lmsrvlabbook/api/mutation.py
  packages/gtmapi/lmsrvlabbook/api/mutations/__init__.py
  packages/gtmapi/lmsrvlabbook/api/mutations/environmentcomponent.py
  packages/gtmapi/lmsrvlabbook/api/mutations/labbook.py
  packages/gtmapi/lmsrvlabbook/api/objects/basecomponent.py
  packages/gtmapi/lmsrvlabbook/api/objects/customcomponent.py
  packages/gtmapi/lmsrvlabbook/api/objects/environment.py
  packages/gtmapi/lmsrvlabbook/api/query.py
  packages/gtmapi/lmsrvlabbook/tests/fixtures.py
  packages/gtmapi/lmsrvlabbook/tests/int_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_environment_base_image_queries.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_environment_component_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_environment_custom_dependency_queries.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_environment_queries.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_base_image_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_component_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_custom_dependency_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_overview.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_queries.py
  packages/gtmcore/gtmcore/configuration/config/labmanager.yaml.default
  packages/gtmcore/gtmcore/dispatcher/tests/test_dispatcher.py
  packages/gtmcore/gtmcore/dispatcher/tests/test_jobs.py
  packages/gtmcore/gtmcore/environment/__init__.py
  packages/gtmcore/gtmcore/environment/componentmanager.py
  packages/gtmcore/gtmcore/environment/repository.py
  packages/gtmcore/gtmcore/environment/repositorymanager.py
  packages/gtmcore/gtmcore/environment/tests/test_componentmanager.py
  packages/gtmcore/gtmcore/environment/tests/test_conda.py
  packages/gtmcore/gtmcore/environment/tests/test_container_fallback.py
  packages/gtmcore/gtmcore/environment/tests/test_environment_repository.py
  packages/gtmcore/gtmcore/environment/tests/test_environment_repository_manager.py
  packages/gtmcore/gtmcore/environment/tests/test_pip.py
  packages/gtmcore/gtmcore/fixtures/container.py
  packages/gtmcore/gtmcore/fixtures/fixtures.py
  packages/gtmcore/gtmcore/imagebuilder/imagebuilder.py
  packages/gtmcore/gtmcore/imagebuilder/tests/test_imagebuilder.py
  packages/gtmcore/gtmcore/labbook/labbook.py
  ui/config/webpack.config.dev.js
  ui/config/webpack.config.prod.js
  ui/schema.graphql
  ui/src/css/atoms/card.scss
  ui/src/js/components/dashboard/labbooks/localLabbooks/import/ImportModule.js
  ui/src/js/components/labbook/activity/Activity.js
  ui/src/js/components/labbook/activity/ActivityCard.scss
  ui/src/js/components/labbook/environment/Base.scss
  ui/src/js/components/labbook/environment/CustomDockerfile.scss
  ui/src/js/components/labbook/environment/PackageDependencies.js
  ui/src/js/components/labbook/environment/PackageDependencies.scss
  ui/src/js/components/labbook/labbookHeader/branchMenu/BranchMenu.scss
  ui/src/js/components/labbook/overview/FileEmpty.js
  ui/src/js/components/labbook/overview/Overview.js
  ui/src/js/components/labbook/overview/Overview.scss
  ui/src/js/components/labbook/overview/RecentActivity.scss
  ui/src/js/components/shared/Prompt.js
  ui/src/js/mutations/CreateLabbookMutation.js
Labels: backend, enhancement

#100 72 - Add --no-recommends to apt and -q to conda pkg mngrs
  packages/gtmcore/gtmcore/environment/apt.py
  packages/gtmcore/gtmcore/environment/conda.py
  packages/gtmcore/gtmcore/environment/tests/test_apt.py
  packages/gtmcore/gtmcore/environment/tests/test_conda.py
  packages/gtmcore/gtmcore/imagebuilder/tests/test_imagebuilder.py
Labels: backend, enhancement, feedback-request

#102 Fix bug in proxy route lookup which caused proxy route errors on JupyterLab open
  packages/gtmapi/lmsrvlabbook/api/mutations/container.py
  packages/gtmapi/lmsrvlabbook/api/mutations/environment.py
  packages/gtmcore/gtmcore/container/jupyter.py
  packages/gtmcore/gtmcore/container/tests/test_container_ops.py
  ui/src/js/createRelayEnvironment.js
Labels: backend, bug, priority: high

#108 Package Dependencies Bug Fixes
  ui/config/webpack.config.prod.js
  ui/schema.graphql
  ui/src/js/components/labbook/environment/PackageDependencies.js
  ui/src/js/components/labbook/environment/PackageDependencies.scss
  ui/src/js/components/labbook/labbookHeader/containerStatus/ContainerStatus.js
Labels: bug, frontend

#99 Strengthen zip-import failure handling
  packages/gtmapi/lmsrvlabbook/api/mutations/labbook.py
  packages/gtmapi/lmsrvlabbook/api/objects/labbooklist.py
  packages/gtmapi/lmsrvlabbook/tests/snapshots/snap_test_labbook_remote_ops.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_remote_ops.py
  packages/gtmcore/gtmcore/auth/identity.py
  packages/gtmcore/gtmcore/auth/tests/test_local.py
  packages/gtmcore/gtmcore/configuration/utils.py
  packages/gtmcore/gtmcore/container/container.py
  packages/gtmcore/gtmcore/container/core.py
  packages/gtmcore/gtmcore/container/utils.py
  packages/gtmcore/gtmcore/dispatcher/dispatcher.py
  packages/gtmcore/gtmcore/dispatcher/jobs.py
  packages/gtmcore/gtmcore/dispatcher/tests/test_jobs.py
  packages/gtmcore/gtmcore/labbook/__init__.py
  packages/gtmcore/gtmcore/labbook/inventory.py
  packages/gtmcore/gtmcore/labbook/labbook.py
  packages/gtmcore/gtmcore/workflows/__init__.py
  packages/gtmcore/gtmcore/workflows/tests/snappy.zip
  packages/gtmcore/gtmcore/workflows/tests/test_from_windows.zip
  packages/gtmcore/gtmcore/workflows/tests/test_zips.py
  packages/gtmcore/gtmcore/workflows/workflows.py
  packages/gtmcore/setup.py
  resources/client/supervisord-demo.conf
  resources/client/supervisord-local.conf
  testing/Test_02_ImportExport.py
  ui/schema.graphql
  ui/src/css/components/labbook/containerStatus.scss
  ui/src/css/components/shared/user.scss
  ui/src/js/components/dashboard/labbooks/localLabbooks/LocalLabbookPanel.js
  ui/src/js/components/dashboard/labbooks/localLabbooks/LocalLabbookPanel.scss
  ui/src/js/components/dashboard/labbooks/localLabbooks/import/ImportModule.js
  ui/src/js/components/dashboard/labbooks/remoteLabbooks/RemoteLabbookPanel.js
  ui/src/js/components/dashboard/labbooks/remoteLabbooks/RemoteLabbookPanel.scss
  ui/src/js/components/dashboard/labbooks/remoteLabbooks/RemoteLabbooks.js
  ui/src/js/components/labbook/fileBrowser/FileBrowserWrapper.js
  ui/src/js/components/labbook/fileBrowser/FolderUpload.js
  ui/src/js/components/labbook/labbookHeader/LabbookHeader.scss
  ui/src/js/components/labbook/labbookHeader/branchMenu/BranchMenu.js
  ui/src/js/components/labbook/labbookHeader/containerStatus/ContainerStatus.js
  ui/src/js/components/shared/footer/FooterUtils.js
  ui/src/js/mutations/ImportLabbookMutation.js
  ui/src/js/mutations/container/StartDevToolMutation.js
  ui/src/js/utils/ChunkUploader.js
  ui/src/js/utils/JobStatus.js
Labels: backend, bug, feedback-qa

#187 Refactor parent class for LabBook and reorganize InventoryManager
  packages/gtmapi/lmsrvlabbook/api/mutations/branching.py
  packages/gtmapi/lmsrvlabbook/api/mutations/container.py
  packages/gtmapi/lmsrvlabbook/api/mutations/environment.py
  packages/gtmapi/lmsrvlabbook/api/mutations/environmentcomponent.py
  packages/gtmapi/lmsrvlabbook/api/mutations/labbook.py
  packages/gtmapi/lmsrvlabbook/api/mutations/labbooksharing.py
  packages/gtmapi/lmsrvlabbook/api/mutations/note.py
  packages/gtmapi/lmsrvlabbook/api/objects/labbook.py
  packages/gtmapi/lmsrvlabbook/api/objects/labbooklist.py
  packages/gtmapi/lmsrvlabbook/api/objects/remotelabbook.py
  packages/gtmapi/lmsrvlabbook/dataloader/labbook.py
  packages/gtmapi/lmsrvlabbook/tests/fixtures.py
  packages/gtmapi/lmsrvlabbook/tests/int_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_dataloader_labbook.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_component_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_environment_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_collaborator_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_overview.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_remote_ops.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_share_protocol.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_sharing.py
  packages/gtmapi/lmsrvlabbook/tests/test_node_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_note_service.py
  packages/gtmapi/lmsrvlabbook/tests/test_upload_files_mutations.py
  packages/gtmapi/lmsrvlabbook/tests/test_workflows_branching.py
  packages/gtmapi/service.py
  packages/gtmcore/gtmcore/activity/monitors/activity.py
  packages/gtmcore/gtmcore/activity/store.py
  packages/gtmcore/gtmcore/container/container.py
  packages/gtmcore/gtmcore/container/core.py
  packages/gtmcore/gtmcore/container/jupyter.py
  packages/gtmcore/gtmcore/dispatcher/jobs.py
  packages/gtmcore/gtmcore/dispatcher/tests/test_dispatcher.py
  packages/gtmcore/gtmcore/dispatcher/tests/test_jobs.py
  packages/gtmcore/gtmcore/environment/componentmanager.py
  packages/gtmcore/gtmcore/environment/tests/test_componentmanager.py
  packages/gtmcore/gtmcore/environment/tests/test_container_fallback.py
  packages/gtmcore/gtmcore/exceptions/__init__.py
  packages/gtmcore/gtmcore/exceptions/exceptions.py
  packages/gtmcore/gtmcore/fixtures/container.py
  packages/gtmcore/gtmcore/fixtures/fixtures.py
  packages/gtmcore/gtmcore/inventory/__init__.py
  packages/gtmcore/gtmcore/inventory/inventory.py
  packages/gtmcore/gtmcore/inventory/repository.py
  packages/gtmcore/gtmcore/inventory/tests/__init__.py
  packages/gtmcore/gtmcore/inventory/tests/test_inventory.py
  packages/gtmcore/gtmcore/inventory/tests/test_process_sweep_status.py
  packages/gtmcore/gtmcore/labbook/__init__.py
  packages/gtmcore/gtmcore/labbook/labbook.py
  packages/gtmcore/gtmcore/labbook/loaders.py
  packages/gtmcore/gtmcore/labbook/shims.py
  packages/gtmcore/gtmcore/labbook/tests/test_labbook.py
  packages/gtmcore/gtmcore/labbook/tests/test_labbook_lock.py
  packages/gtmcore/gtmcore/labbook/tests/test_labbook_sharing.py
  packages/gtmcore/gtmcore/workflows/core.py
  packages/gtmcore/gtmcore/workflows/tests/test_zips.py
  packages/gtmcore/gtmcore/workflows/workflows.py
Labels: backend, enhancement
