Repository gigantum/gigantum-client, pull requests merged in 2019-01, with the labels that each got.

#345 remove excess console logs
  ui/scripts/gitignore.js
Labels: bug

#406 hotfix (#395)
  ui/src/js/components/Routes.js
Labels: bug, ux

#430 hotfix - Fix demo project import bug
  packages/gtmcore/gtmcore/workflows/zipworkflow.py
  ui/src/css/components/shared/user.scss
  ui/src/js/components/labbook/labbookHeader/LabbookHeader.js
  ui/src/js/components/labbook/labbookHeader/LabbookHeader.scss
  ui/src/js/components/labbook/labbookHeader/branches/Branches.scss
Labels: bug

#445 194: Add project modified datetime to API and cards
  packages/gtmapi/lmsrvlabbook/api/objects/labbook.py
  packages/gtmapi/lmsrvlabbook/tests/test_dataset_queries.py
  packages/gtmapi/lmsrvlabbook/tests/test_labbook_queries.py
  packages/gtmapi/requirements-testing.txt
  packages/gtmcore/gtmcore/dataset/dataset.py
  packages/gtmcore/gtmcore/dataset/tests/test_dataset.py
  packages/gtmcore/gtmcore/inventory/repository.py
  packages/gtmcore/gtmcore/inventory/tests/test_inventory.py
  packages/gtmcore/gtmcore/inventory/tests/test_inventory_datasets.py
  packages/gtmcore/gtmcore/labbook/labbook.py
  packages/gtmcore/gtmcore/labbook/tests/test_labbook.py
  ui/schema.graphql
  ui/src/js/components/dashboard/datasets/Datasets.js
  ui/src/js/components/dashboard/datasets/localDatasets/LocalDatasets.js
  ui/src/js/components/dashboard/labbooks/localLabbooks/LocalLabbookPanel.js
  ui/src/js/components/dashboard/labbooks/localLabbooks/LocalLabbooks.js
Labels: enhancement
